# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download runway.bin
        run: |
          wget https://runwaydownloads.blob.core.windows.net/appdl/runway.bin
          chmod +x ./runway.bin

      - name: Auth to Runway
        run: |
          ./runway.bin login -u ${{ secrets.RUNWAY_EMAIL }} -p ${{ secrets.RUNWAY_PASSWORD }}

      - name: Build Each Action on PR
        if: ${{ github.event_name == 'pull_request' }}
        shell: pwsh
        run: ./script.ps1 -Test
      
      - name: Publish Each Action on Push
        if: ${{ github.event_name == 'push' }}
        shell: pwsh
        run: ./script.ps1